### PR TITLE
added more config options

### PR DESCRIPTION
**Pull request by Sickboy78**
added toggles for current weather and text summary (for when using another module like currentweather and you dont want redundancy)
added fading option for last two forecast rows

### CODE REVIEW

**Comment by dmcinnes** [comment]
Sorry I’m lagging on reviews, mind fixing your indentation?

**Review by dmcinnes — CHANGES_REQUESTED** [review]
Also mind fixing conflicts?

**Comment by Sickboy78** [comment]
Conflicts fixed.
Also hope I got the indentation right this time.

**Review by dmcinnes — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
