### PR TITLE
added Sunrise and Sunset times

### PR DESCRIPTION
**Pull request by morozgrafix**
Added optional display of the sunrise and sunset times.
boolean `showSunriseSunset` config parameter toggles display

It looks like this:
image

### CODE REVIEW

**Comment by lavolp3** [comment]
Using HH:mm timeformat the implementation looked a bit crowded to me. The time was too close to the symbol.

Would suggest to inlcude this into the css:
`.MMM-forecast-io .extras>span {
  padding-right: 0.3em;
}
`
image

**Comment by morozgrafix** [comment]
Good call. I will add some CSS styles to it.

**Review by dmcinnes — CHANGES_REQUESTED** [review]
Looks great! I agree with @lavolp3's suggestion, add that and I'll merge.

**Comment by morozgrafix** [comment]
padding added to the sunset and sunrise icons, while keeping rest of the info aligned to the right to match rest of the text. Let me know if this works better. Thanks.

**Review by dmcinnes — APPROVED** [review]

**Pull request merged**
