### PR TITLE
Added support for indoor temperature

### PR DESCRIPTION
**Pull request by idoodler**
MMM-forecast-io is missing support for `INDOOR_TEMPERATURE`, I am needing it for a module I am developing.

It listens for this notification and display the indoor temperature on the right side of the current outside temperature with a little house icon.

temp

### CODE REVIEW

**Review by dmcinnes — CHANGES_REQUESTED** [review]
Hey cool! I may be able to do this myself. Will you please submit only the changes you want to add and not reformat all the code? Please also make the new code match formatting with the original.

**Comment by dmcinnes** [comment]
“I may be able to _use_ this myself” sorry

**Comment by idoodler** [comment]
@dmcinnes Ok, I will revert the format changes. I didn't really bother the change, but you are right:)

I will update the PR ASAP.

**Comment by idoodler** [comment]
@dmcinnes I just updated the PR and removed all the reformatting.

**Review by dmcinnes — APPROVED** [review]

**Comment by dmcinnes** [comment]
Thanks! Sorry I missed your update.

**Pull request merged**
