### PR TITLE
minutely PrecipitationGraph

### PR DESCRIPTION
**Pull request by barondh**
following up issue "Precipitation Graph does not display / loads endlessly #10": Is there a way to implement the precipitation graph for areas where no minutely updates are available?

### CODE REVIEW

**Comment by dmcinnes** [comment]
Looks like you may have the base backwards..should be `into master from weather-forecast-psudo-elements` instead of `weather-forecast-psudo-elements from master`.
Mind fixing it?

**Comment by barondh** [comment]
thanks for your reply. I must admitt Iäm a complete noob. Didn't understand
much of what you just wrote. Sorry for my ingorance...

2017-12-08 1:08 GMT+01:00 Doug McInnes <notifications@github.com>:

**Comment by lavolp3** [comment]
PR #21 seems to resolve the issue as well so this could be rejected, since it is set up in the wrong direction

**Comment by dmcinnes** [comment]
Closing this in favor of #21

**Pull request closed without merging**
